# fly.toml app configuration file generated for technical-test-backend-wandering-field-2655-rough-glitter-1482 on 2023-11-30T19:37:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "technical-test-backend-wandering-field-2655-rough-glitter-1482"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
